### ISSUE TITLE
Handle seat limit logic while they are selecting seats?

### ISSUE THREAD

**Issue by sikander441** [littledivy/pune-interstellar-screening#4]
Why wait till checkout to let them know that they cannot select more than 4 seats, this can be handled in `handleSeatToggle` to stop them from selecting more than 4, just better UX imo

https://github.com/littledivy/pune-interstellar-screening/blob/a6ac9bd0687d5300b3ed63262fc7a6d457d9051f/islands/Seats.tsx#L43

**Comment by littledivy** [comment]
Fixed, thanks
